table:
  name: recipes
  schema: public
object_relationships:
  - name: category
    using:
      foreign_key_constraint_on: category_id
  - name: user
    using:
      foreign_key_constraint_on: user_id
array_relationships:
  - name: bookmarks
    using:
      foreign_key_constraint_on:
        column: recipe_id
        table:
          name: bookmarks
          schema: public
  - name: comments
    using:
      foreign_key_constraint_on:
        column: recipe_id
        table:
          name: comments
          schema: public
  - name: ingredients
    using:
      foreign_key_constraint_on:
        column: recipe_id
        table:
          name: ingredients
          schema: public
  - name: likes
    using:
      foreign_key_constraint_on:
        column: recipe_id
        table:
          name: likes
          schema: public
  - name: purchases
    using:
      foreign_key_constraint_on:
        column: recipe_id
        table:
          name: purchases
          schema: public
  - name: ratings
    using:
      foreign_key_constraint_on:
        column: recipe_id
        table:
          name: ratings
          schema: public
  - name: recipe_images
    using:
      foreign_key_constraint_on:
        column: recipe_id
        table:
          name: recipe_images
          schema: public
  - name: steps
    using:
      foreign_key_constraint_on:
        column: recipe_id
        table:
          name: steps
          schema: public
insert_permissions:
  - role: user
    permission:
      check:
        user_id:
          _eq: X-Hasura-User-Id
      columns:
        - category_id
        - description
        - featured_image
        - is_premium
        - prep_time
        - price
        - title
    comment: ""
select_permissions:
  - role: anonymous
    permission:
      columns:
        - category_id
        - created_at
        - description
        - featured_image
        - id
        - prep_time
        - title
        - updated_at
        - user_id
      filter:
        is_premium:
          _eq: false
    comment: ""
  - role: user
    permission:
      columns:
        - category_id
        - created_at
        - description
        - id
        - is_premium
        - prep_time
        - price
        - title
        - updated_at
        - user_id
      filter:
        _or:
          - is_premium:
              _eq: false
          - purchases:
              user_id:
                _eq: X-Hasura-User-Id
          - user_id:
              _eq: X-Hasura-User-Id
    comment: ""
update_permissions:
  - role: user
    permission:
      columns:
        - category_id
        - description
        - featured_image
        - is_premium
        - prep_time
        - price
        - title
        - updated_at
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      check: null
    comment: ""
delete_permissions:
  - role: user
    permission:
      filter:
        user_id:
          _eq: X-Hasura-User-Id
    comment: ""