table:
  name: purchases
  schema: public
object_relationships:
  - name: recipe
    using:
      foreign_key_constraint_on: recipe_id
  - name: user
    using:
      foreign_key_constraint_on: user_id
insert_permissions:
  - role: user
    permission:
      check: {}
      columns:
        - user_id
    comment: ""
select_permissions:
  - role: user
    permission:
      columns:
        - amount
        - chapa_transaction_id
        - created_at
        - id
        - recipe_id
        - status
        - user_id
      filter:
        user_id:
          _eq: X-Hasura-User-Id
    comment: ""