table:
  name: likes
  schema: public
object_relationships:
  - name: recipe
    using:
      foreign_key_constraint_on: recipe_id
  - name: user
    using:
      foreign_key_constraint_on: user_id
insert_permissions:
  - role: user
    permission:
      check:
        user_id:
          _eq: X-Hasura-User-Id
      columns:
        - recipe_id
        - user_id
    comment: ""
select_permissions:
  - role: anonymous
    permission:
      columns:
        - created_at
        - id
        - recipe_id
      filter:
        _exists:
          _table:
            name: likes
            schema: public
          _where: {}
    comment: ""
  - role: user
    permission:
      columns:
        - created_at
        - id
        - recipe_id
        - user_id
      filter:
        _exists:
          _table:
            name: likes
            schema: public
          _where: {}
    comment: ""
delete_permissions:
  - role: user
    permission:
      filter:
        user_id:
          _eq: X-Hasura-User-Id
    comment: ""