- name: default
  kind: postgres
  configuration:
    connection_info:
      database_url:
        from_env: HASURA_GRAPHQL_DATABASE_URL
      isolation_level: read-committed
      pool_settings:
        connection_lifetime: 600
        idle_timeout: 180
        max_connections: 50
        retries: 1
      use_prepared_statements: true
  tables: []

- name: spatuladb
  kind: postgres
  configuration:
    connection_info:
      database_url: postgres://postgres:lancetdb@postgres:5432/spatuladb
      isolation_level: read-committed
      use_prepared_statements: false
  tables:
  - "spatuladb/tables/public_bookmarks.yaml"
  - "spatuladb/tables/public_categories.yaml"
  - "spatuladb/tables/public_comments.yaml"
  - "spatuladb/tables/public_ingredients.yaml"
  - "spatuladb/tables/public_likes.yaml"
  - "spatuladb/tables/public_purchases.yaml"
  - "spatuladb/tables/public_ratings.yaml"
  - "spatuladb/tables/public_recipe_images.yaml"
  - "spatuladb/tables/public_recipes.yaml"
  - "spatuladb/tables/public_steps.yaml"
  - "spatuladb/tables/public_users.yaml"