- name: default
  kind: postgres
  configuration:
    connection_info:
      database_url:
        from_env: HASURA_GRAPHQL_DATABASE_URL
      isolation_level: read-committed
      pool_settings:
        connection_lifetime: 600
        idle_timeout: 180
        max_connections: 50
        retries: 1
      use_prepared_statements: true
  tables: []

- name: spatuladb
  kind: postgres
  configuration:
    connection_info:
      database_url: postgres://postgres:lancetdb@postgres:5432/spatuladb
      isolation_level: read-committed
      use_prepared_statements: false
  tables:
    - "!include public_bookmarks.yaml"
    - "!include public_categories.yaml"
    - "!include public_comments.yaml"
    - "!include public_ingredients.yaml"
    - "!include public_likes.yaml"
    - "!include public_purchases.yaml"
    - "!include public_ratings.yaml"
    - "!include public_recipe_images.yaml"
    - "!include public_recipes.yaml"
    - "!include public_steps.yaml"
    - "!include public_users.yaml"